# Main config file
# Define things like DB name, ports, JWT expiry, etc.
# remember to put all the fields
env: prod # prod/dev

database:
  host: "localhost"
  name: "compass"
  # FIXME(prod): Create new user id
  user: "this_is_mjk"
  port: 5432

rabbitmq:
  host: "localhost"
  # FIXME(prod): Create new user id and pwd
  user: "this_is_mjk"
  password: "guest"
  mailqueue: "mail_queue" # Keep the names consistent <type>queue for protect the publish logic correct
  moderationqueue: "moderation_queue"
  port: 5672

ports:
  auth: 8080
  maps: 8081
  assets: 8082
  search: 8083

smtp:
  host: smtp.gmail.com
  port: 587

domain: ""
# Browsers rewrite Domain=localhost cookies into .localhost, which breaks host-only cookie checks.
# Fix: leave domain empty ("") in dev so the cookie is scoped only to localhost

frontend_url: "https://bauth.pclub.in" # Dev: http://localhost:3000, Prod: https://auth.pclub.in

expiry:
  emailVerification: 3

# TODO: Understand how can we change the configs in run time
image:
  quality: 40

noticeboard:
  limit: 5
